### ISSUE TITLE
Fixing Compatibility with updated d3d8to9

### ISSUE THREAD

**Issue by romulus2k4** [elishacloud/BloodRayne-2-Patch#3]
Hello.

I was wondering if it would be possible to update this to enable support for updated version of Crosire's d3d8to9? It'd greatly help with Reshade support.

**Comment by elishacloud** [comment]
Done!  This project has been updated to use the latest version of d3d8to9.  You can get the new release [here](https://github.com/elishacloud/BloodRayne-2-Patch/releases/tag/v1.0.3.0).

**Comment by romulus2k4** [comment]
Thank you so much!

**Comment by romulus2k4** [comment]
Okay, some feedback.

Seems the issue I was previously encountering wasn't resolved by simply updating Crosire's d3d8to9 for this patch.

Here's the issue in it's entirety: 

If I use the d3d8.dll that is included within this patch, ReShade works and can inject Shaders successfully into the game. The intro cinematic at the startup of the game works fine, However, upon starting a new game (that triggers a FMV cinematic) or selecting any level that switches to loading a FMV cinematic, crashes the game immediately. Alt+Tab introduces a crash too. Levels that do not trigger a cinematic loads and plays fine with no crashes.

If I swap the d3d8.dll with the latest release of Crosire's d3d8to9, the game  in conjunction with ReShade no longer crashes. but it disables all Perlin based effects. This game receives a huge face lift once ReShade is applied, and your input is much appreciated.

On another note, the BR FSAA 1.0.0.0 patch had an issue where it wouldn't highlight enemies when targeted/focused on, which seems to have been fixed through this update.

**Comment by elishacloud** [comment]
I created an update that makes the 'd3d8patch.dll' file optional.  You can try with this one:  [br2-Patch.zip](https://github.com/elishacloud/BloodRayne-2-Patch/files/3105441/br2-Patch.zip)

I am not able to reproduce the issue.  It never crashed for me.  I am using the following ReShade files: [ReShade.zip](https://github.com/elishacloud/BloodRayne-2-Patch/files/3105459/ReShade.zip)

I suspect it either has to do with some ReShade settings or some 'BR FSAA' patch setting.

_Note: it looks like the cinematic videos are played from 'cutscene.exe'.  I could just exclude this process to avoid the issue.  Or I could make it so that the functions are enabled only for 'br2.exe'._

**Comment by romulus2k4** [comment]
Okay, I tried the new BR2 FSAA patch and your ReShade package, which both resulted in a crash. After some digging, I was able to figure out that disabling "Enhanced Dynamic Reflections" the game no longer crashes while switching to FMVs in game in conjunction with ReShade. Not using D3D8Patch.dll file causes all BR FSAA patch related effects to not work at all, therefore it didn't crash when you tried to reproduce the issue, another reason for not crashing is that you probably didn't have that specific option enabled during your testing.

**Comment by elishacloud** [comment]
The D3D8Patch.dll file is the BR2 FSAA patch file.  If that is removed or renamed then the BR2 FSAA patch gets disabled.  I ran tests both with and without the D3D8Patch.dll file.  It did not crash.

The "Enhanced Dynamic Reflections" feature was enabled for all my tests:

![BR2 FSAA Enhancements](https://user-images.githubusercontent.com/25625456/56626726-bd5fa400-65f7-11e9-8ab4-e1d6048a7da2.png)

I don't have the source code for the BR2 FSAA patch.  My project here just wraps the BR2 FSAA patch to fix a few issues with it when using Windows 10.

The issue you are having could be related to the program you are using for playing the cutscenes.  The game supports different programs to play the cutscenes.  Here are the files I am using.  Copy all three of these files into the BloodRayne 2 folder.   [Cutscene.zip](https://github.com/elishacloud/BloodRayne-2-Patch/files/3110232/cutscene.zip)

**Comment by romulus2k4** [comment]
The Cutscene.zip file you've provided has the same generic videoplayer that ships with the game. Regardless of what program I use to play cutscene during the game, the moment I enable Enhanced Dynamic Reflections along with ReShade, it will crash whenever an in game cutscene is triggered.  

I guess there's not much to do, the logs don't state any reasons for the crash either. Thank you very much for your efforts. Updating to the latest Direct3D8to9 has fixed enemies not being highlighted when focused on, which is a great bonus which I didn't think was possible! So, there's that.

Enabling that Enhanced Dynamic Reflections also messes up ReShade's MXAO implementation which makes objects that shouldn't be transparent, transparent. So, in a way, that option not working isn't a big loss.

**Comment by elishacloud** [comment]
The difference in our tests could be based on the version of the game we are using or our video cards.  I am running the [GOG](https://www.gog.com/game/bloodrayne_2) version of the game and I am using an Nvidia 780 GTX video card.  In the next update I will add these items to the log file.

However if you are ok to run it without 'Enhanced Dynamic Reflections' then everything is good.  But if you want to troubleshoot this I would open a ticket in [ReShade](https://reshade.me/forum).  It is likely that any change to fix this would need to be done in ReShade.

**Comment by romulus2k4** [comment]
I have all three versions of the game, and with the GPU I currently have (which is an AMD HD 5770 1GB) this could probably be a driver issue or some sort of incompatibility, I'll be able to check this once I get to my workplace where I have access to newer video cards. And yes, I'll try and open a ticker over at ReShade or their official forum to see if the MXAO issue and this crash can be resolved, assuming it's not a problem with my current GPU/Driver combination, as they are a bit dated.

**Comment by elishacloud** [comment]
Closing issue.
