### ISSUE TITLE
I'm using the Master release and the game won't launch at all.

### ISSUE THREAD

**Issue by Mexaddon** [elishacloud/BloodRayne-2-Patch#5]
Hi. I have a GoG copy of the game installed through Galaxy 2.0. The game won't launch at all with the patch installed. I've tried it on 4 fresh installs. On the last one, I didn't even modify or launch the br2fsaaConfig.exe at all - I merely put the 9 files from the folder called "BR2.FSAA.Patch.1.666" into BloodRayne 2's main folder. It didn't run even then.

This is the error that's being registered on errorlog:

![BloodRayne 2 error](https://user-images.githubusercontent.com/67302262/85355736-e8cb7080-b4d2-11ea-9fc5-60c15d9aef07.png)

Any help is greatly appreciated.

**Comment by TP555** [comment]
Hi

your System Specs , GPU  ??

Try with DGVoodoo , but then you lost all new Settings / HD Textures from the FSSA Patch
But you can than mayby run it without FSSA Patch

For Missing Widescreen , look then at WSGF or pcgamingwiki.com

**Comment by elishacloud** [comment]
This patch does support GOG.  I am using the GOG version of BloodRayne 2.  However, by default the FSSA patch does _not_ work on all GPUs.

You need to run the `br2fsaaConfig.exe` config tool and configure the settings correctly for your GPU.    If you don't know the settings then chose the "Auto Config" option.  This should configure all the settings to work on your GPU

![image](https://user-images.githubusercontent.com/25625456/98073263-cbad9380-1e1c-11eb-87aa-99cf4e9dedd2.png)

**Comment by FrostMoonEcho** [comment]
I had the same issue. Just use the auto config and select dunno options

**Comment by FrostMoonEcho** [comment]
@elishacloud The main reason why I need this stuff is to resize the hud but it doesn't work for me at all on Blood Rayne 2 Terminal Cut. I'm ready to pay money for that work. For example, some ASI patch. Would you be interested in it?

**Comment by elishacloud** [comment]
@FrostMoonEcho, I just published a new release.  You can download it here:  https://github.com/elishacloud/BloodRayne-2-Patch/releases/tag/v1.1.17.0

I have not tried the Terminal Cut to know if it works with the br2fsaa patch.  Unfortunately, the source code to the br2fsaa patch isn't available so we cannot easily make changes to it.

If the updated doesn't work then try these steps:

1. Disable all compatibility options in the BloodRayne 2 executable except "Run program as an administrator"
2. Run the br2fsaa Config tool and setup your Cut Scene.  Make sure to test it and then save the cut scene settings.
3. Try enabling the new `GraphicsHybridAdapter` option I added in the d3d8.ini file.

![Image](https://github.com/user-attachments/assets/65cea799-0639-4c1e-a1e6-5c22530ee1bd)

![Image](https://github.com/user-attachments/assets/c39d361b-4a7e-4b4d-bfa5-c17b8c580290)

**Comment by FrostMoonEcho** [comment]
@elishacloud Hi! Glad to meet you again :) The new option GraphicsHybridAdapter works perfectly well.

Unfortunately, the HUD resizing still doesn't work. My steps were:

1. Make a clean installation of Terminal Cut
2. Add br2fsaa tool
3. Make sure that compatibility options are disabled for the game and tool
4. Launch the br2fsaa tool as an administrator and start auto config. Then resize the hud and setup cutsene.
5. Configure GPU in Nvidia Control Panel
5. Launch game executable as an administrator. At this point I see my GPU and don't experience any troubles with launching the game. But the size of the HUD in the left upper corner remains unchanged

P.S. Also I can't select all my CPUs in  br2fsaa tool. I have at least 6 physical ones

**Comment by elishacloud** [comment]
> The new option GraphicsHybridAdapter works perfectly well.

OK, very good.

> Unfortunately, the HUD resizing still doesn't work.

How are you trying to do HUD resizing?  Are you using the br2fsaa tool to do that?  There is an option in the "HUD" tab in the br2fsaa tool.  Make sure to click "Save Config" after modifying the HUD size.

BTW: I just tested this in BloodRayne 2 base edition.  It could be that the HUD feature in br2fsaa doesn't work in the Terminal Cut.

> Also I can't select all my CPUs in br2fsaa tool. I have at least 6 physical ones

Don't worry about that.  Just set it for dual or quad CPU.  Also, you can set up 6 CPU threads from the "CPU" tab in the br2fsaa tool.  You can also set it for SSE3.  Again, make sure you click "Save Config" after modifying any setting in the br2fsaa tool.

**Comment by FrostMoonEcho** [comment]
> > The new option GraphicsHybridAdapter works perfectly well.
> 
> OK, very good.
> 
> > Unfortunately, the HUD resizing still doesn't work.
> 
> How are you trying to do HUD resizing? Are you using the br2fsaa tool to do that? There is an option in the "HUD" tab in the br2fsaa tool. Make sure to click "Save Config" after modifying the HUD size.

Yes, I did it exactly this way. I tried several times to do that, but it looked like it didn't work with Terminal Cut at all.

> > Also I can't select all my CPUs in br2fsaa tool. I have at least 6 physical ones
> 
> Don't worry about that. Just set it for dual or quad CPU. Also, you can set up 6 CPU threads from the "CPU" tab in the br2fsaa tool. You can also set it for SSE3. Again, make sure you click "Save Config" after modifying any setting in the br2fsaa tool.

Thanks, I'm going to try that. I guess CPU management is a very complicated thing. I have more than twenty CPUs on my laptop, but only six of them are useful indeed. This is the amount that I have after disabling virtual and power saving ones.

**Comment by elishacloud** [comment]
> Yes, I did it exactly this way. I tried several times to do that, but it looked like it didn't work with Terminal Cut at all.

I suspect that this feature won't work on the Terminal Cut.  It would require code changes to the br2fsaa wrapper, which as I mentioned we don't have the code.  It may be possible that this could be done in my wrapper I created for this project.  But I am not working on adding specific game features like that.  I am working on generic tools and not individual games like this.
